<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TagEmpresa', 'doctrine');

/**
 * BaseTagEmpresa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $tag_id
 * @property integer $empresa_id
 * 
 * @method integer    getId()         Returns the current record's "id" value
 * @method integer    getTagId()      Returns the current record's "tag_id" value
 * @method integer    getEmpresaId()  Returns the current record's "empresa_id" value
 * @method TagEmpresa setId()         Sets the current record's "id" value
 * @method TagEmpresa setTagId()      Sets the current record's "tag_id" value
 * @method TagEmpresa setEmpresaId()  Sets the current record's "empresa_id" value
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTagEmpresa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tag_empresa');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('tag_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('empresa_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}