<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Institucion', 'doctrine');

/**
 * BaseInstitucion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $coordenada_x
 * @property string $coordenada_y
 * @property string $telefono_1
 * @property string $telefono_2
 * @property string $imagen
 * @property integer $tipo
 * @property integer $ciudad_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer     getId()           Returns the current record's "id" value
 * @method string      getNombre()       Returns the current record's "nombre" value
 * @method string      getCoordenadaX()  Returns the current record's "coordenada_x" value
 * @method string      getCoordenadaY()  Returns the current record's "coordenada_y" value
 * @method string      getTelefono1()    Returns the current record's "telefono_1" value
 * @method string      getTelefono2()    Returns the current record's "telefono_2" value
 * @method string      getImagen()       Returns the current record's "imagen" value
 * @method integer     getTipo()         Returns the current record's "tipo" value
 * @method integer     getCiudadId()     Returns the current record's "ciudad_id" value
 * @method timestamp   getCreatedAt()    Returns the current record's "created_at" value
 * @method timestamp   getUpdatedAt()    Returns the current record's "updated_at" value
 * @method Institucion setId()           Sets the current record's "id" value
 * @method Institucion setNombre()       Sets the current record's "nombre" value
 * @method Institucion setCoordenadaX()  Sets the current record's "coordenada_x" value
 * @method Institucion setCoordenadaY()  Sets the current record's "coordenada_y" value
 * @method Institucion setTelefono1()    Sets the current record's "telefono_1" value
 * @method Institucion setTelefono2()    Sets the current record's "telefono_2" value
 * @method Institucion setImagen()       Sets the current record's "imagen" value
 * @method Institucion setTipo()         Sets the current record's "tipo" value
 * @method Institucion setCiudadId()     Sets the current record's "ciudad_id" value
 * @method Institucion setCreatedAt()    Sets the current record's "created_at" value
 * @method Institucion setUpdatedAt()    Sets the current record's "updated_at" value
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInstitucion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('institucion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('coordenada_x', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('coordenada_y', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('telefono_1', 'string', 12, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 12,
             ));
        $this->hasColumn('telefono_2', 'string', 12, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 12,
             ));
        $this->hasColumn('imagen', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('tipo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ciudad_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}