<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UsuarioPreferencia', 'doctrine');

/**
 * BaseUsuarioPreferencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $correo_publico
 * @property integer $usuario_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer            getId()             Returns the current record's "id" value
 * @method integer            getCorreoPublico()  Returns the current record's "correo_publico" value
 * @method integer            getUsuarioId()      Returns the current record's "usuario_id" value
 * @method timestamp          getCreatedAt()      Returns the current record's "created_at" value
 * @method timestamp          getUpdatedAt()      Returns the current record's "updated_at" value
 * @method UsuarioPreferencia setId()             Sets the current record's "id" value
 * @method UsuarioPreferencia setCorreoPublico()  Sets the current record's "correo_publico" value
 * @method UsuarioPreferencia setUsuarioId()      Sets the current record's "usuario_id" value
 * @method UsuarioPreferencia setCreatedAt()      Sets the current record's "created_at" value
 * @method UsuarioPreferencia setUpdatedAt()      Sets the current record's "updated_at" value
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuarioPreferencia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario_preferencia');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('correo_publico', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}