<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AnuncioEvento', 'doctrine');

/**
 * BaseAnuncioEvento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $coordenada_x
 * @property integer $coordenada_y
 * @property timestamp $fecha_inicio
 * @property timestamp $fecha_fin
 * @property integer $anuncio_id
 * @property integer $ciudad_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer       getId()           Returns the current record's "id" value
 * @method integer       getCoordenadaX()  Returns the current record's "coordenada_x" value
 * @method integer       getCoordenadaY()  Returns the current record's "coordenada_y" value
 * @method timestamp     getFechaInicio()  Returns the current record's "fecha_inicio" value
 * @method timestamp     getFechaFin()     Returns the current record's "fecha_fin" value
 * @method integer       getAnuncioId()    Returns the current record's "anuncio_id" value
 * @method integer       getCiudadId()     Returns the current record's "ciudad_id" value
 * @method timestamp     getCreatedAt()    Returns the current record's "created_at" value
 * @method timestamp     getUpdatedAt()    Returns the current record's "updated_at" value
 * @method AnuncioEvento setId()           Sets the current record's "id" value
 * @method AnuncioEvento setCoordenadaX()  Sets the current record's "coordenada_x" value
 * @method AnuncioEvento setCoordenadaY()  Sets the current record's "coordenada_y" value
 * @method AnuncioEvento setFechaInicio()  Sets the current record's "fecha_inicio" value
 * @method AnuncioEvento setFechaFin()     Sets the current record's "fecha_fin" value
 * @method AnuncioEvento setAnuncioId()    Sets the current record's "anuncio_id" value
 * @method AnuncioEvento setCiudadId()     Sets the current record's "ciudad_id" value
 * @method AnuncioEvento setCreatedAt()    Sets the current record's "created_at" value
 * @method AnuncioEvento setUpdatedAt()    Sets the current record's "updated_at" value
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnuncioEvento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('anuncio_evento');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('coordenada_x', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('coordenada_y', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_inicio', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_fin', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('anuncio_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ciudad_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}