<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AnuncioCupon', 'doctrine');

/**
 * BaseAnuncioCupon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $cantidad
 * @property integer $cantidad_restante
 * @property integer $cantidad_persona
 * @property date $fecha_inicio
 * @property date $fecha_fin
 * @property timestamp $fecha_disfrute_inicio
 * @property timestamp $fecha_disfrute_fin
 * @property integer $anuncio_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer      getId()                    Returns the current record's "id" value
 * @method integer      getCantidad()              Returns the current record's "cantidad" value
 * @method integer      getCantidadRestante()      Returns the current record's "cantidad_restante" value
 * @method integer      getCantidadPersona()       Returns the current record's "cantidad_persona" value
 * @method date         getFechaInicio()           Returns the current record's "fecha_inicio" value
 * @method date         getFechaFin()              Returns the current record's "fecha_fin" value
 * @method timestamp    getFechaDisfruteInicio()   Returns the current record's "fecha_disfrute_inicio" value
 * @method timestamp    getFechaDisfruteFin()      Returns the current record's "fecha_disfrute_fin" value
 * @method integer      getAnuncioId()             Returns the current record's "anuncio_id" value
 * @method timestamp    getCreatedAt()             Returns the current record's "created_at" value
 * @method timestamp    getUpdatedAt()             Returns the current record's "updated_at" value
 * @method AnuncioCupon setId()                    Sets the current record's "id" value
 * @method AnuncioCupon setCantidad()              Sets the current record's "cantidad" value
 * @method AnuncioCupon setCantidadRestante()      Sets the current record's "cantidad_restante" value
 * @method AnuncioCupon setCantidadPersona()       Sets the current record's "cantidad_persona" value
 * @method AnuncioCupon setFechaInicio()           Sets the current record's "fecha_inicio" value
 * @method AnuncioCupon setFechaFin()              Sets the current record's "fecha_fin" value
 * @method AnuncioCupon setFechaDisfruteInicio()   Sets the current record's "fecha_disfrute_inicio" value
 * @method AnuncioCupon setFechaDisfruteFin()      Sets the current record's "fecha_disfrute_fin" value
 * @method AnuncioCupon setAnuncioId()             Sets the current record's "anuncio_id" value
 * @method AnuncioCupon setCreatedAt()             Sets the current record's "created_at" value
 * @method AnuncioCupon setUpdatedAt()             Sets the current record's "updated_at" value
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnuncioCupon extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('anuncio_cupon');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cantidad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cantidad_restante', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cantidad_persona', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_inicio', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_fin', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_disfrute_inicio', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_disfrute_fin', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('anuncio_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}