<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UsuarioRedSocial', 'doctrine');

/**
 * BaseUsuarioRedSocial
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $red_social
 * @property string $perfil
 * @property integer $usuario_id
 * @property integer $created_at
 * @property integer $updated_at
 * 
 * @method integer          getId()         Returns the current record's "id" value
 * @method string           getRedSocial()  Returns the current record's "red_social" value
 * @method string           getPerfil()     Returns the current record's "perfil" value
 * @method integer          getUsuarioId()  Returns the current record's "usuario_id" value
 * @method integer          getCreatedAt()  Returns the current record's "created_at" value
 * @method integer          getUpdatedAt()  Returns the current record's "updated_at" value
 * @method UsuarioRedSocial setId()         Sets the current record's "id" value
 * @method UsuarioRedSocial setRedSocial()  Sets the current record's "red_social" value
 * @method UsuarioRedSocial setPerfil()     Sets the current record's "perfil" value
 * @method UsuarioRedSocial setUsuarioId()  Sets the current record's "usuario_id" value
 * @method UsuarioRedSocial setCreatedAt()  Sets the current record's "created_at" value
 * @method UsuarioRedSocial setUpdatedAt()  Sets the current record's "updated_at" value
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuarioRedSocial extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario_red_social');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('red_social', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('perfil', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('updated_at', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}