<?php

/**
 * AnuncioOfertaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnuncioOfertaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnuncioOfertaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnuncioOferta');
    }
}