<?php

/**
 * DenunciaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DenunciaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DenunciaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Denuncia');
    }
}