<?php

/**
 * InstitucionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InstitucionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InstitucionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Institucion');
    }
}