<?php

/**
 * SucursalAnuncioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SucursalAnuncioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SucursalAnuncioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SucursalAnuncio');
    }
}