<?php

/**
 * SucursalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SucursalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SucursalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sucursal');
    }
}