<?php

/**
 * TagEmpresaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagEmpresaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TagEmpresaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TagEmpresa');
    }
}