<?php

/**
 * UsuarioRedSocialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioRedSocialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuarioRedSocialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsuarioRedSocial');
    }
}